---
# ###-- Patching machines with latest stable versions
- name: Install yum utils
  package:
    name:
    - yum-utils
    - "@Development tools"
    lock_timeout: 180

- name: Update all packages to the latest version
  yum:
    name: '*'
    state: latest
  become: true

- name: Install policycoreutils package 
  yum:
    name: policycoreutils
    state: present
  
- name: Set SELinux to enforcing mode
  selinux:
    policy: targeted
    state: enforcing
  become: true

- name: Install SELinux policy package
  yum:
    name: selinux-policy
    state: present

- name: Disable SELinux
  selinux:
    state: enforcing


# ###-- SSH port configuration from port 22 to port 2222
- name: Change SSH port number.
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^Port"
    line: "Port 2222"

- name: Setup Selinux for SSH Port.
  seport:
    ports: "2222"
    proto: "tcp"
    setype: "ssh_port_t"
    state: "present"


###--- Disable root login
- name: Comment PermitRootLogin in SSH Config file.
  replace:
    path: /etc/ssh/sshd_config
    regexp: "PermitRootLogin yes"
    replace: "#PermitRootLogin no"


###--- Configure and enable firewall rule 
- name: Install firewalld package
  yum:
    name: firewalld
    state: present
  become: true
- name: Start firewalld service
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Firewall rule.
  firewalld:
    port: 2222/tcp
    permanent: yes
    zone: public
    state: enabled
    immediate: yes

- name: Firewall rule.
  firewalld:
    port: 22/tcp
    permanent: yes
    zone: public
    state: enabled
    immediate: yes

- name: Firewall rule for HTTP (port 80)
  firewalld:
    port: 80/tcp
    zone: public
    permanent: yes
    state: enabled
    immediate: yes

- name: Restart sshd service
  service:
    name: sshd
    state: restarted


###--- Configure haproxy on lb server
- name: Ensure HAProxy is installed.
  package:
    name: haproxy
    state: present

- name: Ensure HAProxy is enabled (so init script will start it on Debian).
  lineinfile:
    dest: /etc/default/haproxy
    regexp: "^ENABLED.+$"
    line: "ENABLED=1"
    state: present
  when: ansible_os_family == 'Debian'

- name: Get HAProxy version.
  command: haproxy -v
  register: haproxy_version_result
  changed_when: false
  check_mode: false

- name: Set HAProxy version.
  set_fact:
    haproxy_version: '{{ haproxy_version_result.stdout_lines[0] | regex_replace("^HA-?Proxy version (\d+(\.\d+)*).*$", "\1") }}'

- name: Copy HAProxy configuration in place.
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: restart haproxy

- name: Ensure HAProxy is started and enabled on boot.
  service:
    name: haproxy
    state: started
    enabled: yes

###--- Non-Root Accounts Have UID Set To 0
- name: Display accounts with UID set to 0
  ansible.builtin.shell:
    cmd: "awk -F: '($3 == \"0\") {print}' /etc/passwd"
  register: root_accounts_output
  changed_when: false

- name: Show output
  debug:
    msg: "{{ root_accounts_output.stdout_lines }}"
