---
###-- Patching machines with latest stable versions
- name: Install yum utils
  package:
    name:
      - yum-utils
      - "@Development tools"
    lock_timeout: 180

- name: Update all packages to the latest version
  yum:
    name: "*"
    state: latest
  become: true

- name: Add cron job  to patch update at 1am everyday
  cron:
    name: "Your Cron Job Name"
    minute: "0"
    hour: "1"
    job: "yum update"
  become: true

- name: Ensure SELINUX=enforcing in /etc/selinux/config
  lineinfile:
    path: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=enforcing"
    state: present
  notify: Reboot if SELinux state changed

- name: Set SELinux to Enforcing mode
  command: setenforce 1

- name: OS_hardening
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: { { item.regexp } }
    line: { { item.line } }
  loop:
    - regexp: "^PasswordAuthentication"
      line: "#PasswordAuthentication no"
    - regexp: "^PermitRootLogin"
      line: "#PermitRootLogin yes"
    - regexp: "^Port"
      line: "Port 2222"
    - regexp: "^PermitEmptyPasswords"
      line: "PermitEmptyPasswords no"

- name: Setup Selinux for SSH Port.
  seport:
    ports: "2222"
    proto: "tcp"
    setype: "ssh_port_t"
    state: "present"

- name: Copy SSH key.
  authorized_key:
    user: ec2-user
    state: present
    manage_dir: yes
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

- name: Restart sshd service
  service:
    name: sshd
    state: restarted

##-- Configure and enable firewall rule
- name: Install firewalld package
  yum:
    name: firewalld
    state: present

- name: Start firewalld service
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Firewall rule.
  firewalld:
    port: { { item.port } }
    permanent: yes
    zone: public
    state: enabled
    immediate: yes
  loop:
    - port: 2222/tcp
    - port: 80/tcp

###--- Non-Root Accounts Have UID Set To 0
- name: Display accounts with UID set to 0
  ansible.builtin.shell:
    cmd: "awk -F: '($3 == \"0\") {print}' /etc/passwd"
  register: root_accounts_output
  changed_when: false

- name: Show output
  debug:
    msg: "{{ root_accounts_output.stdout_lines }}"

###-- Configure Apache on app-01 and app-02 webservers
- name: Install Apache web server package
  yum:
    name: httpd
    state: present

- name: Ensure Apache service is started and enabled
  service:
    name: httpd
    state: started
    enabled: true

- name: create html directory
  file:
    path: /var/www/html
    state: directory
    mode: "0755"
    owner: apache
    group: apache

- name: server content
  copy:
    content: "<h1>Hello World, from server IP {{ ansible_host }}<h1>"
    dest: /var/www/html/index.html
    mode: "0755"
    owner: apache
    group: apache
  notify: Restart apache service

